### ISSUE TITLE
Review `which` for inclusion in SDK third_party DEPS.

### ISSUE THREAD

**Issue by pq** [dart-lang/which#9]
I've tagged a release `0.1.3` and would like to include it in the SDK DEPS to add it to `third_party/pkg`.  This is required in order to pull `cli_util` into the SDK.  (Note that `when` will need to be vetted in the same way; issue to follow.)

`cli_util` is used by *at least* the following core dart services:

  * `analyzer_cli`
  * `dartdoc`
  * `linter`
  * `analysis_server`

Please consider this a review of the whole corpus.  I'll respond to concerns with a separate pull request and then update the tag before referencing it in DEPS.

Reviewers:

@devoncarew
@sethladd

**Comment by pq** [comment]
Review of `when`: dart-lang/when#6.

**Comment by devoncarew** [comment]
lgtm :)

**Comment by sethladd** [comment]
lgtm
